---
- name: Install needed deps
  apt:
    name: ["sshfs"]
    update_cache: yes

- name: tell the host about our servers it might want to ssh to
  known_hosts:
    path: /root/.ssh/known_hosts
    name: "{{ sshmount_item.remotehost }}"
    key: "{{ lookup('pipe', 'ssh-keyscan {{ sshmount_item.remotehost }} 2>/dev/null') }}"
  loop: "{{ servermounts if servermounts is defined else [] }}"
  when:
    - servermounts is defined
    - sshmount_item.remotehost is defined
  loop_control:
    loop_var: sshmount_item

- name: add mountpoints
  mount:
    path: "{{ mount_item.mountpoint }}"
    src: "{{ mount_item.dev }}"
    fstype: "{{ mount_item.fstype }}"
    opts: "{{ mount_item.opts }}"
    state: mounted
  loop: "{{ servermounts if servermounts is defined else [] }}"
  when:
    - servermounts is defined
  loop_control:
    loop_var: mount_item
